name: "🤖 Track New Model"
description: Request SCAPO to start tracking a new AI model
title: "[Model]: "
labels: ["new-model", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Request SCAPO to start tracking a new model. Once added, SCAPO will automatically extract practices from our sources when this model is mentioned.

  - type: input
    id: model-name
    attributes:
      label: Model Name
      description: Official name of the model
      placeholder: "GPT-4 Turbo"
    validations:
      required: true

  - type: input
    id: model-id
    attributes:
      label: Model ID
      description: Lowercase ID with hyphens (we'll use this for file paths)
      placeholder: "gpt-4-turbo"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Model Category
      description: Where it belongs in models/ directory
      options:
        - text (Language models)
        - image (Image generation)
        - video (Video generation)
        - audio (Audio/Speech)
        - multimodal (Multi-modal models)
    validations:
      required: true

  - type: input
    id: developer
    attributes:
      label: Developer/Company
      placeholder: "OpenAI, Anthropic, Meta, etc."
    validations:
      required: true

  - type: textarea
    id: model-info
    attributes:
      label: Model Information
      description: Tell us about this model
      placeholder: |
        - Release date: 
        - Key capabilities:
        - Common use cases:
        - Notable features:
        - API/Access method:

  - type: textarea
    id: sources
    attributes:
      label: Where is this model discussed?
      description: Help us find sources for best practices
      placeholder: |
        - r/LocalLLaMA frequently discusses this model
        - Official Discord: discord.gg/example
        - Documentation: https://docs.example.com
        - Community forum: https://forum.example.com

  - type: textarea
    id: model-directory
    attributes:
      label: Expected Directory Structure
      description: This model will be tracked at models/{category}/{model-id}/
      value: |
        Once added, SCAPO will create:
        - models/{category}/{model-id}/prompting.md
        - models/{category}/{model-id}/parameters.json
        - models/{category}/{model-id}/pitfalls.md
        - models/{category}/{model-id}/examples/tips.json
        - models/{category}/{model-id}/metadata.json
        
        And automatically populate these from scraped sources.

  - type: dropdown
    id: urgency
    attributes:
      label: How popular/important is this model?
      options:
        - Very popular - used by many
        - Growing interest
        - Niche but important
        - Just released
    validations:
      required: true

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I'd like to help add this model
        - label: I can provide prompt examples
        - label: I can share parameter recommendations