name: "🐛 Bug Report"
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: |
        When I run the Reddit scraper, it fails with...
        
        Expected: Successfully scrape posts
        Actual: Error message about...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Clone the repository
        2. Run `make quickstart`
        3. Execute `python -m src.scrapers.run reddit`
        4. See error
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Message/Logs
      description: Copy the full error message or relevant logs
      render: shell

  - type: dropdown
    id: component
    attributes:
      label: Which component is affected?
      options:
        - Scrapers
        - API Server
        - MCP Server
        - Database/Models
        - CLI
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Windows 11, macOS 13, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.12.0"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've checked existing issues
        - label: I've validated my configuration
        - label: I'm using the latest version