name: "✨ Feature Request"
description: Suggest an idea or improvement for SCAPO
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make SCAPO better! 🚀

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What kind of feature are you requesting?
      options:
        - New AI service support
        - Scraping improvement
        - Data extraction enhancement
        - UI/UX improvement
        - API feature
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        I'm always frustrated when...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Optional - any other approaches you've thought about

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
        - label: I can provide test cases or examples
        - label: I can help with documentation