# SCAPO Scraping Sources Configuration
# This file contains all approved sources for automated scraping
# Each source includes scraping method, rate limits, and content focus

reddit:
  description: "Reddit communities focused on AI/ML practices"
  api: "PRAW (Python Reddit API Wrapper)"
  rate_limit: "100 requests/minute per app"
  auth: "OAuth2 with client credentials"
  sources:
    - name: "r/PromptEngineering"
      url: "https://www.reddit.com/r/PromptEngineering/"
      focus: "Prompt patterns, evaluation threads, paper links"
      priority: high
      models: ["gpt-4", "claude", "llama", "general"]
    
    - name: "r/LocalLLM"
      url: "https://www.reddit.com/r/LocalLLM/"
      focus: "Running LLMs offline, hardware configs, benchmarks"
      priority: high
      models: ["llama", "mistral", "phi", "quantized"]
    
    - name: "r/LocalLLaMA"
      url: "https://www.reddit.com/r/LocalLLaMA/"
      focus: "Model comparisons, quantization techniques"
      priority: high
      models: ["llama", "mistral", "general"]
    
    - name: "r/LLMOps"
      url: "https://www.reddit.com/r/llmops/"
      focus: "Deployment, monitoring, prompt-ops tooling"
      priority: medium
      models: ["general", "infrastructure"]
    
    - name: "r/StableDiffusion"
      url: "https://www.reddit.com/r/StableDiffusion/"
      focus: "Image generation recipes, ControlNet, LoRA"
      priority: high
      models: ["stable-diffusion", "sdxl", "controlnet"]
    
    - name: "r/midjourney"
      url: "https://www.reddit.com/r/midjourney/"
      focus: "Midjourney prompts and parameters"
      priority: high
      models: ["midjourney"]
    
    - name: "r/OpenAI"
      url: "https://www.reddit.com/r/OpenAI/"
      focus: "GPT best practices, API usage"
      priority: high
      models: ["gpt-4", "gpt-3.5", "chatgpt"]
    
    # AI Video Generation Discussion
    - name: "r/ArtificialIntelligence"
      url: "https://www.reddit.com/r/ArtificialIntelligence/"
      focus: "General AI discussions including video generation services"
      priority: critical
      models: ["heygen", "synthesia", "runway", "ai-video", "general"]
    
    - name: "r/Synthesia"  
      url: "https://www.reddit.com/r/artificial/"
      focus: "AI discussions including Synthesia and video generation"
      priority: critical
      models: ["synthesia", "ai-video", "artificial-intelligence"]
    
    - name: "r/RunwayML"
      url: "https://www.reddit.com/r/MediaSynthesis/"
      focus: "Media synthesis discussions including Runway and AI video"
      priority: critical
      models: ["runway", "gen-3", "gen-4", "video-generation"]
    
    - name: "r/DID"
      url: "https://www.reddit.com/search/?q=d-id+tips+OR+d-id+tricks+OR+\"d-id+tutorial\"+OR+\"d-id+prompt\"+OR+\"d-id+best+practices\"+OR+\"d-id+settings\""
      focus: "Talking head generation, credit management, API optimization"
      priority: high
      models: ["d-id", "talking-head"]
    
    - name: "r/LumaAI"
      url: "https://www.reddit.com/search/?q=luma+ai+tips+OR+luma+ai+tricks+OR+\"luma+ai+tutorial\"+OR+\"luma+ai+prompt\"+OR+\"luma+ai+best+practices\"+OR+\"dream+machine+tips\""
      focus: "Dream Machine optimization, 3D generation tips"
      priority: high
      models: ["luma-ai", "dream-machine"]
    
    - name: "r/PikaLabs"
      url: "https://www.reddit.com/search/?q=pika+labs+tips+OR+pika+labs+tricks+OR+\"pika+labs+prompt\"+OR+\"pika+labs+tutorial\"+OR+\"pika+labs+best+practices\"+OR+\"pika+settings\""
      focus: "Video generation prompting, parameter optimization"
      priority: high  
      models: ["pika-labs", "pika-2"]
    
    # AI Voice Generation Services
    - name: "r/ElevenLabs"
      url: "https://www.reddit.com/r/ElevenLabs/"
      focus: "Voice cloning optimization, character management, batch processing"
      priority: critical
      models: ["elevenlabs", "voice-cloning"]
    
    - name: "r/MurfAI"
      url: "https://www.reddit.com/search/?q=murf+ai+tips+OR+murf+ai+tricks+OR+\"murf+ai+tutorial\"+OR+\"murf+ai+prompt\"+OR+\"murf+ai+best+practices\"+OR+\"murf+settings\""
      focus: "Professional voiceover optimization, cost management"
      priority: high
      models: ["murf", "voiceover"]
    
    - name: "r/PlayHT"
      url: "https://www.reddit.com/search/?q=play.ht+tips+OR+\"play ht\"+optimization"
      focus: "Voice synthesis optimization, API usage"
      priority: medium
      models: ["play-ht", "voice-synthesis"]
    
    # AI Image Generation Services
    - name: "r/LeonardoAI"
      url: "https://www.reddit.com/search/?q=leonardo+ai+tips+OR+\"leonardo ai\"+optimization"
      focus: "Credit optimization, model selection, batch generation"
      priority: high
      models: ["leonardo-ai", "image-generation"]
    
    - name: "r/Ideogram"
      url: "https://www.reddit.com/search/?q=ideogram+tips+OR+ideogram+optimization"
      focus: "Text rendering optimization, prompt engineering"
      priority: medium
      models: ["ideogram", "text-image"]
    
    # AI Coding Services
    - name: "r/GitHubCopilot"
      url: "https://www.reddit.com/search/?q=github+copilot+tips+OR+copilot+optimization"
      focus: "Code completion optimization, productivity tips, shortcuts"
      priority: high
      models: ["github-copilot", "copilot"]
    
    - name: "r/Cursor"
      url: "https://www.reddit.com/search/?q=cursor+ai+tips+OR+cursor+optimization"
      focus: "AI-first IDE optimization, workflow tips"
      priority: high
      models: ["cursor", "ai-ide"]
    
    - name: "r/Codeium"
      url: "https://www.reddit.com/search/?q=codeium+tips+OR+codeium+optimization"
      focus: "Code completion, refactoring, cost optimization"
      priority: medium
      models: ["codeium", "code-assistant"]
    
    # Virtual Influencer Services  
    - name: "r/CharacterAI"
      url: "https://www.reddit.com/r/CharacterAI/"
      focus: "Character creation optimization, prompt engineering, memory management"
      priority: high
      models: ["character-ai", "ai-character"]
    
    - name: "r/Replika"
      url: "https://www.reddit.com/r/replika/"
      focus: "AI companion optimization, conversation flow, subscription tips"
      priority: medium
      models: ["replika", "ai-companion"]
    
    # Enterprise AI Services
    - name: "r/ScaleAI"
      url: "https://www.reddit.com/search/?q=scale+ai+tips+OR+\"scale ai\"+optimization"
      focus: "Data labeling optimization, model training efficiency"
      priority: medium
      models: ["scale-ai", "data-labeling"]
    
    # Virtual Influencer Business Optimization
    - name: "r/VirtualInfluencerBusiness"
      url: "https://www.reddit.com/search/?q=(subreddit:entrepreneur+OR+subreddit:marketing+OR+subreddit:OnlyFansAdvice+OR+subreddit:passive_income)+AND+(\"virtual+influencer+profit\"+OR+\"AI+model+income\"+OR+\"digital+persona+monetization\"+OR+\"avatar+business+model\"+OR+\"AI+girlfriend+revenue\")"
      focus: "Monetization strategies and ROI optimization for virtual influencers"
      priority: ultra
      models: ["glambase", "ai-influencer", "virtual-persona"]
    
    - name: "r/AIInfluencerTech" 
      url: "https://www.reddit.com/search/?q=(subreddit:MachineLearning+OR+subreddit:artificial+OR+subreddit:ChatGPT)+AND+(\"virtual+influencer\"+OR+\"AI+persona\"+OR+\"digital+human+business\"+OR+\"avatar+automation\")"
      focus: "Technical optimization for AI influencer platforms"
      priority: ultra
      models: ["virtual-influencer", "ai-persona", "digital-human"]
    
    # Persistent World Services
    - name: "r/SpatialOS"
      url: "https://www.reddit.com/search/?q=spatialos+tips+OR+spatialos+tricks+OR+\"spatialos+tutorial\"+OR+\"spatialos+best+practices\"+OR+\"spatial+os+tips\"+OR+\"improbable+tips\""
      focus: "SpatialOS cost optimization, deployment strategies, enterprise usage"
      priority: ultra
      models: ["spatialos", "improbable"]
    
    - name: "r/UnityCloud"
      url: "https://www.reddit.com/search/?q=unity+cloud+pricing+OR+multiplay+hosting+costs"
      focus: "Unity Cloud cost management, server optimization, multiplayer scaling"
      priority: ultra
      models: ["unity-cloud", "multiplay"]
    
    # AI Companion Enterprise Services
    - name: "r/ReplicaBusiness"
      url: "https://www.reddit.com/search/?q=replika+business+OR+\"ai companion\"+enterprise"
      focus: "Enterprise AI companion deployment, B2B optimization"
      priority: ultra
      models: ["replika-enterprise", "ai-companion-b2b"]
    
    - name: "r/CharacterAIBusiness"
      url: "https://www.reddit.com/search/?q=character.ai+business+OR+\"character ai\"+enterprise"
      focus: "Character.AI enterprise features, scaling, cost management"
      priority: ultra
      models: ["character-ai-enterprise", "c-ai-business"]
    
    # Digital Human/Avatar Discussion
    - name: "r/AvatarCosts"
      url: "https://www.reddit.com/r/ChatGPT/"
      focus: "AI service discussions including avatars and digital humans"
      priority: ultra
      models: ["soul-machines", "digital-human", "ai-avatar", "heygen", "synthesia"]
    
    - name: "r/DigitalHuman"
      url: "https://www.reddit.com/search/?q=\"digital+human\"+tips+OR+\"digital+human\"+tricks+OR+\"digital+human\"+tutorial+OR+\"avatar+tips\"+OR+\"avatar+best+practices\""
      focus: "Enterprise digital human solutions, deployment optimization"
      priority: ultra
      models: ["digital-human-enterprise", "avatar-enterprise"]
    
    # Latest AI Models
    - name: "r/GPT5"
      url: "https://www.reddit.com/search/?q=gpt-5+tips+OR+gpt5+tricks+OR+\"gpt+5\"+tips+OR+\"gpt-5\"+tutorial+OR+\"gpt-5\"+prompt+OR+\"gpt-5\"+best+practices"
      focus: "GPT-5 optimization, cost management, advanced features"
      priority: critical
      models: ["gpt-5", "gpt5"]
    
    - name: "r/Claude4"
      url: "https://www.reddit.com/search/?q=claude+4+tips+OR+\"claude 4\"+optimization"
      focus: "Claude 4 advanced features, cost optimization, prompt engineering"
      priority: critical
      models: ["claude-4", "claude4"]
    
    - name: "r/ClaudeAI"
      url: "https://www.reddit.com/r/ClaudeAI/"
      focus: "Claude usage patterns and tips"
      priority: high
      models: ["claude-4", "claude-opus-4", "claude-sonnet-4"]
    
    - name: "r/generativeAI"
      url: "https://www.reddit.com/r/generativeAI/"
      focus: "Broad GenAI Q&A, education, tooling"
      priority: medium
      models: ["general"]
    
    
    - name: "r/comfyui"
      url: "https://www.reddit.com/r/comfyui/"
      focus: "ComfyUI workflows and nodes"
      priority: medium
      models: ["stable-diffusion", "comfyui"]
    
    - name: "r/singularity"
      url: "https://www.reddit.com/r/singularity/"
      focus: "AI advances and discussions"
      priority: low
      models: ["general"]

github:
  description: "GitHub repositories with structured AI best practices"
  api: "GitHub API v4 (GraphQL) or raw.githubusercontent.com"
  rate_limit: "5000 requests/hour authenticated"
  auth: "Personal Access Token (PAT)"
  sources:
    - name: "DAIR-AI Prompt Engineering Guide"
      url: "https://github.com/dair-ai/Prompt-Engineering-Guide"
      raw_url: "https://raw.githubusercontent.com/dair-ai/Prompt-Engineering-Guide/main/README.md"
      focus: "Research papers, cheat-sheets, prompt engineering courses"
      license: "CC-BY-SA-4.0"
      priority: high
      update_frequency: "weekly"
    
    - name: "Awesome Prompt Engineering"
      url: "https://github.com/promptslab/Awesome-Prompt-Engineering"
      raw_url: "https://raw.githubusercontent.com/promptslab/Awesome-Prompt-Engineering/main/README.md"
      focus: "Curated links to papers, tools, datasets, prompt patterns"
      license: "MIT"
      priority: high
      update_frequency: "weekly"
    
    - name: "Awesome Generative AI"
      url: "https://github.com/steven2358/awesome-generative-ai"
      raw_url: "https://raw.githubusercontent.com/steven2358/awesome-generative-ai/main/README.md"
      focus: "Broader GenAI resources, models, frameworks"
      license: "CC0"
      priority: medium
      update_frequency: "biweekly"
    
    - name: "Brex Prompt Engineering"
      url: "https://github.com/brexhq/prompt-engineering"
      raw_url: "https://raw.githubusercontent.com/brexhq/prompt-engineering/main/README.md"
      focus: "Corporate best practices, guardrails, evaluation"
      license: "Apache-2.0"
      priority: high
      update_frequency: "monthly"
    
    - name: "OpenAI Cookbook"
      url: "https://github.com/openai/openai-cookbook"
      focus: "Example code and guides for OpenAI API"
      license: "MIT"
      priority: high
      update_frequency: "weekly"
    
    - name: "LangChain Documentation"
      url: "https://github.com/langchain-ai/langchain"
      focus: "Agent patterns, chain examples"
      license: "MIT"
      priority: medium
      update_frequency: "daily"

forums:
  description: "Developer forums with structured discussions"
  sources:
    - name: "OpenAI Community Forum"
      url: "https://community.openai.com"
      api: "Discourse JSON endpoints"
      endpoints:
        latest: "https://community.openai.com/latest.json"
        categories: "https://community.openai.com/categories.json"
        search: "https://community.openai.com/search.json"
      focus: "Production guardrails, rate-limit workarounds"
      priority: high
      rate_limit: "60 requests/minute"
    
    - name: "Hugging Face Forums"
      url: "https://discuss.huggingface.co"
      api: "Discourse JSON endpoints"
      focus: "Model fine-tuning, deployment tips"
      priority: high
      rate_limit: "60 requests/minute"
    
    - name: "AIPRM Community Forum"
      url: "https://forum.aiprm.com"
      api: "Discourse JSON endpoints"
      focus: "SEO-oriented prompt tweaks"
      priority: low
      rate_limit: "60 requests/minute"

apis:
  description: "Direct API access to prompt/practice databases"
  sources:
    - name: "LangChain Hub"
      url: "https://smith.langchain.com/hub"
      api: "REST & Python client"
      sdk: "langchain.hub"
      focus: "Community-maintained prompt chains"
      auth: "API key"
      priority: high
      example_endpoint: "https://api.smith.langchain.com/v1/public/prompts"
    
    - name: "Hugging Face Datasets"
      url: "https://huggingface.co/datasets"
      api: "Datasets library"
      focus: "Prompt templates, evaluation datasets"
      priority: high
      specific_datasets:
        - "bigscience/promptsource"
        - "databricks/databricks-dolly-15k"
        - "OpenAssistant/oasst1"
    
    - name: "Papers with Code"
      url: "https://paperswithcode.com"
      api: "REST API v0"
      endpoints:
        tasks: "https://paperswithcode.com/api/v0/tasks/"
        papers: "https://paperswithcode.com/api/v0/papers/"
      focus: "Benchmarks, best implementations"
      priority: medium
      rate_limit: "100 requests/hour"


rss_feeds:
  description: "RSS/Atom feeds for blog content"
  sources:
    - name: "DEV.to GenerativeAI tag"
      url: "https://dev.to/feed/tag/generativeai"
      format: "RSS"
      focus: "How-to posts, code examples"
      priority: medium
    
    - name: "Towards Data Science - AI"
      url: "https://towardsdatascience.com/feed"
      format: "RSS"
      focus: "Technical deep-dives"
      priority: low
    
    - name: "AI Alignment Forum"
      url: "https://www.alignmentforum.org/feed.xml"
      format: "RSS"
      focus: "Safety practices, alignment techniques"
      priority: low

news_aggregators:
  description: "High-signal news and discussion aggregators"
  sources:
    - name: "Hacker News"
      url: "https://news.ycombinator.com"
      api: "Firebase API"
      endpoints:
        top: "https://hacker-news.firebaseio.com/v0/topstories.json"
        item: "https://hacker-news.firebaseio.com/v0/item/{id}.json"
        search: "https://hn.algolia.com/api/v1/search"
      focus: "Technical discussions, new tools"
      priority: high
      tags_to_track: ["gpt", "llm", "prompt", "ai", "genai"]

# Scraping Configuration
scraping_config:
  user_agent: "Mozilla/5.0 (compatible; SCAPOBot/1.0; +https://github.com/czero-cc/scapo)"
  respect_robots_txt: true
  concurrent_requests: 5
  timeout_seconds: 30
  retry_attempts: 3
  cache_duration_hours: 24
  
# Content Filtering
content_filters:
  min_score: 10  # Minimum upvotes/score
  min_comments: 5  # Minimum engagement
  keywords:
    include:
      - "prompt"
      - "parameter"
      - "best practice"
      - "tip"
      - "trick"
      - "optimal"
      - "recommended"
      - "setting"
      - "config"
      - "guide"
      - "tutorial"
      - "workflow"
    exclude:
      - "meme"
      - "joke"
      - "shitpost"
      - "[deleted]"
      - "[removed]"